name: Data Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # roda todo dia à meia-noite

jobs:
  build_and_collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Instala Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Instala dependências
      - name: Install dependencies
        run: npm install

      # Executa testes simulados
      - name: Run tests
        run: node scripts/test.js

      # Executa coleta de dados
      - name: Collect and register events
        run: node scripts/collectData.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
